Repository Somfic/1.3-SchoolPlanner, pull requests merged in 2022-02, with the labels that each got.

#17 Feature/settingscreen
  .idea/encodings.xml
  SchoolPlanner.iml
  src/Data/Classroom.java
  src/Data/Gender.java
  src/Data/Lesson.java
  src/Data/Person.java
  src/Data/Schedule.java
  src/Data/ScheduleItem.java
  src/Data/Student.java
  src/Data/StudentGroup.java
  src/Data/Teacher.java
  src/Gui/Dropdown.java
  src/Gui/Gui.java
  src/Gui/ScheduleView.java
  src/Gui/SettingsScreen/ClassBlock.java
  src/Gui/SettingsScreen/ClassBlockCallback.java
  src/Gui/SettingsScreen/ColorCallback.java
  src/Gui/SettingsScreen/ColorSelector.java
  src/Gui/SettingsScreen/SettingView.java
  src/Gui/SettingsScreen/SpeedSelector.java
  src/Gui/SettingsScreen/SpeedSelectorCallback.java
  src/Main.java
Labels: Rooster

#19 Feature/pop up
  .gitignore
  .idea/misc.xml
  .idea/runConfigurations/SchoolPlanner.xml
  src/Gui/Gui.java
  src/Gui/PopUpAddItems.java
  src/Gui/ScheduleView.java
Labels: Rooster

#21 Feature/6buttons
  src/Data/ScheduleItem.java
  src/Gui/SelectButtons.java
Labels: Rooster

#25 Feature/custom window
  SchoolPlanner.iml
  res/Icon.png
  src/Gui/Gui.java
  src/Gui/WindowBar.java
Labels: Other

#29 Added file serialization (Save & Load buttons)
  src/Data/ScheduleItem.java
  src/Gui/Gui.java
  src/Gui/ScheduleView.java
  src/Gui/SelectButtons.java
  src/IO/FileManager.java
Labels: Rooster

#30 Feature/schedule functionality
  .gitignore
  .idea/misc.xml
  .idea/runConfigurations.xml
  src/Data/Classroom.java
  src/Data/Lesson.java
  src/Data/Person.java
  src/Data/Schedule.java
  src/Data/ScheduleItem.java
  src/Gui/Gui.java
  src/Gui/ScheduleView.java
  src/Gui/SelectButtons.java
  src/Gui/WindowBar.java
  src/IO/FileManager.java
Labels: Rooster

#39 Added fixes for schedule bugs
  src/Data/Schedule.java
Labels: Rooster

#41 Dropdown 2.0
  src/Gui/Dropdown.java
  src/Gui/SelectButtons.java
  src/Gui/SettingsScreen/FastBreak.java
  src/Gui/SettingsScreen/LunchBreak.java
Labels: Other

#42 Starttime
  SchoolPlanner.iml
  lib/jfoenix/jfoenix-8.0.10.jar
  src/Gui/Gui.java
  src/Gui/ScheduleView.java
  src/Gui/SettingsScreen/SettingCallback.java
  src/Gui/SettingsScreen/SettingView.java
  src/Gui/SettingsScreen/StartTime.java
  src/Gui/SettingsScreen/StartTimeCallback.java
Labels: Settings

#45 Configed NullPointExeption and color update
  SchoolPlanner.iml
  src/Gui/Gui.java
  src/Gui/ScheduleView.java
  src/Gui/SettingsScreen/ColorSelector.java
  src/Gui/SettingsScreen/SettingView.java
  src/Gui/SettingsScreen/StartTime.java
Labels: Settings
