Repository Somfic/1.3-SchoolPlanner, pull requests merged in 2022-03, with the labels that each got.

#47 Readme awesomeness
  README.md
  res/Icon-highres.png
Labels: Other

#49 Logging systeem
  src/Data/Schedule.java
  src/Gui/Schedule/SelectButtons.java
  src/IO/FileManager.java
  src/Logging/LogLevel.java
  src/Logging/LogListener.java
  src/Logging/Logger.java
Labels: Other

#50 Inladen van Tiles werelden
  res/isometric_grass_and_water.png
  res/isometric_grass_and_water.tmj
  src/Data/Map/Map.java
  src/Data/Map/Tile.java
  src/Data/Tiles/Tiles.java
  src/Data/Tiles/TilesColor.java
  src/Data/Tiles/TilesGrid.java
  src/Data/Tiles/TilesLayer.java
  src/Data/Tiles/TilesTileOffset.java
  src/Data/Tiles/TilesTileSet.java
  src/Data/Tiles/TilesWangSet.java
  src/Data/Tiles/TilesWangTile.java
  src/Gui/Gui.java
  src/Gui/Simulation/SimulationView.java
  src/IO/FileManager.java
Labels: Visualisatie

#58 Feature/fps counter
  src/Data/FramesPerSecond.java
  src/Gui/Gui.java
Labels: Visualisatie

#57 InputManager
  src/Gui/Gui.java
  src/IO/InputManager.java
Labels: Simulatie

#68 Feature/remember settings
  .gitignore
  src/gui/Gui.java
  src/gui/components/WindowBar.java
  src/gui/settings/ClassBlock.java
  src/gui/settings/ColorSelector.java
  src/gui/settings/FastBreak.java
  src/gui/settings/LunchBreak.java
  src/gui/settings/SettingCallback.java
  src/gui/settings/SettingView.java
  src/gui/settings/SpeedSelector.java
  src/gui/settings/StartTime.java
  src/saving/ColorDeserializer.java
  src/saving/LocalTimeDeserializer.java
  src/saving/LocalTimeSerializer.java
  src/saving/settingsSave.txt
Labels: Settings
