Repository Somfic/1.3-SchoolPlanner, pull requests merged in 2022-04, with the labels that each got.

#70 Feature/simulation camera
  res/npc.png
  res/school.tmj
  src/data/FramesPerSecond.java
  src/data/Schedule.java
  src/data/ScheduleItem.java
  src/data/StudentGroup.java
  src/data/map/Map.java
  src/data/map/Tile.java
  src/gui/GameNode.java
  src/gui/Gui.java
  src/gui/Simulation/GameNode.java
  src/gui/Simulation/Npc.java
  src/gui/Simulation/PathFinder.java
  src/gui/schedule/ScheduleChangeCallback.java
  src/gui/schedule/ScheduleView.java
  src/gui/schedule/SelectButtons.java
  src/gui/simulation/Camera.java
  src/gui/simulation/MapInfo.java
  src/gui/simulation/MousePicker.java
  src/gui/simulation/SimulationView.java
  src/gui/simulation/StudentNpc.java
  src/gui/simulation/TeacherNpc.java
  src/io/InputManager.java
  src/saving/settingsSave.txt
Labels: Visualisatie, Simulatie

#72 Feature/multipleteachers
  src/data/Schedule.java
Labels: Rooster, Bug

#71 Feature/add new schedule item
  SchoolPlanner.iml
  src/Gui/Components/Dropdown.java
  src/Gui/Schedule/ScheduleView.java
  src/data/Classroom.java
  src/data/Lesson.java
  src/data/Person.java
  src/data/ScheduleItem.java
  src/data/Student.java
  src/data/Teacher.java
  src/gui/Gui.java
  src/gui/schedule/PopUpAddItems.java
  src/gui/schedule/SelectButtons.java
  src/gui/settings/FastBreak.java
  src/gui/settings/LunchBreak.java
  src/gui/settings/StartTime.java
Labels: Rooster, Bug

#74 NPCs
  src/data/ScheduleItem.java
  src/gui/Gui.java
  src/gui/Simulation/Npc.java
  src/gui/Simulation/PathFinder.java
  src/gui/schedule/ScheduleView.java
  src/gui/schedule/SelectButtons.java
  src/gui/settings/SettingView.java
  src/gui/simulation/SimulationView.java
Labels: Simulatie

#75 Added Sprites for male and female teachers and students
  res/npcSprites.png
  src/gui/Simulation/Npc.java
  src/gui/simulation/StudentNpc.java
  src/gui/simulation/TeacherNpc.java
Labels: Visualisatie

#76 NPCs
  src/gui/simulation/MapInfo.java
  src/gui/simulation/SimulationView.java
  src/gui/simulation/TeacherNpc.java
Labels: Visualisatie, Simulatie

#79 Feature/rotating npc sprites
  res/npcSprites.png
  res/npcSpritesPSFile.psd
  src/data/NpcSorter.java
  src/data/StudentGroup.java
  src/gui/Simulation/Npc.java
  src/gui/simulation/SimulationView.java
  src/gui/simulation/StudentNpc.java
  src/gui/simulation/TeacherNpc.java
Labels: Visualisatie

#81 Improved sprite rotation
  src/gui/Gui.java
  src/gui/Simulation/Npc.java
  src/gui/simulation/SimulationView.java
Labels: Visualisatie

#80 Only run simulation while in the simulation tab
  src/gui/Gui.java
  src/gui/simulation/SimulationView.java
Labels: Simulatie

#82 Configed bug in overwriting excisting lessons.
  src/data/Schedule.java
  src/data/StudentGroup.java
  src/gui/schedule/ScheduleView.java
  src/gui/simulation/SimulationView.java
Labels: Bug
